receivers:
  otlp:
    protocols:
      grpc:
      http:
<<<<<<< HEAD:Logging/config.yaml
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 5s
          static_configs:
            - targets: [localhost:8888]
=======

>>>>>>> 9e8898f (changes made for metrics):Logging/otel-collector-config.yaml
exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]

    metrics:
      receivers: [otlp]
      exporters: [debug]

    logs:
      receivers: [otlp]
      exporters: [debug]